name: BuilderDelight
version: 1.0
main: me.maanraj514.builderdelight.BuilderDelight
api-version: 1.20
commands:
  buildmode:
    description: Gets you into build mode!
    usage: /buildmode
permissions:
  builderdelight.command.buildmode:
    description: Allows you to get into build mode